// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _SPARK_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// SysMatEigen
SEXP SysMatEigen(SEXP Min);
RcppExport SEXP _SPARK_SysMatEigen(SEXP MinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Min(MinSEXP);
    rcpp_result_gen = Rcpp::wrap(SysMatEigen(Min));
    return rcpp_result_gen;
END_RCPP
}
// SparseSysMatEigen
SEXP SparseSysMatEigen(SEXP Min, SEXP num_topin);
RcppExport SEXP _SPARK_SparseSysMatEigen(SEXP MinSEXP, SEXP num_topinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Min(MinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type num_topin(num_topinSEXP);
    rcpp_result_gen = Rcpp::wrap(SparseSysMatEigen(Min, num_topin));
    return rcpp_result_gen;
END_RCPP
}
// CovariatesAI
SEXP CovariatesAI(SEXP Yin, SEXP Xin, SEXP Din, SEXP tauin, SEXP fixtauin, SEXP tolin);
RcppExport SEXP _SPARK_CovariatesAI(SEXP YinSEXP, SEXP XinSEXP, SEXP DinSEXP, SEXP tauinSEXP, SEXP fixtauinSEXP, SEXP tolinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Yin(YinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xin(XinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Din(DinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauin(tauinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fixtauin(fixtauinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tolin(tolinSEXP);
    rcpp_result_gen = Rcpp::wrap(CovariatesAI(Yin, Xin, Din, tauin, fixtauin, tolin));
    return rcpp_result_gen;
END_RCPP
}
// noCovariatesAI
SEXP noCovariatesAI(SEXP Yin, SEXP Xin, SEXP Din, SEXP tauin, SEXP fixtauin, SEXP tolin);
RcppExport SEXP _SPARK_noCovariatesAI(SEXP YinSEXP, SEXP XinSEXP, SEXP DinSEXP, SEXP tauinSEXP, SEXP fixtauinSEXP, SEXP tolinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Yin(YinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xin(XinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Din(DinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauin(tauinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fixtauin(fixtauinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tolin(tolinSEXP);
    rcpp_result_gen = Rcpp::wrap(noCovariatesAI(Yin, Xin, Din, tauin, fixtauin, tolin));
    return rcpp_result_gen;
END_RCPP
}
// ComputeTestQuantRcpp_nocov
SEXP ComputeTestQuantRcpp_nocov(SEXP yin, SEXP Pyin, SEXP cov_matin, SEXP Din, SEXP tauin);
RcppExport SEXP _SPARK_ComputeTestQuantRcpp_nocov(SEXP yinSEXP, SEXP PyinSEXP, SEXP cov_matinSEXP, SEXP DinSEXP, SEXP tauinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type yin(yinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Pyin(PyinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cov_matin(cov_matinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Din(DinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauin(tauinSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeTestQuantRcpp_nocov(yin, Pyin, cov_matin, Din, tauin));
    return rcpp_result_gen;
END_RCPP
}
// ComputeTestQuantRcpp_cov
SEXP ComputeTestQuantRcpp_cov(SEXP yin, SEXP Pyin, SEXP Xin, SEXP cov_matin, SEXP Din, SEXP tauin);
RcppExport SEXP _SPARK_ComputeTestQuantRcpp_cov(SEXP yinSEXP, SEXP PyinSEXP, SEXP XinSEXP, SEXP cov_matinSEXP, SEXP DinSEXP, SEXP tauinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type yin(yinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Pyin(PyinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xin(XinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cov_matin(cov_matinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Din(DinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauin(tauinSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeTestQuantRcpp_cov(yin, Pyin, Xin, cov_matin, Din, tauin));
    return rcpp_result_gen;
END_RCPP
}
// ComputeTestQuantRcpp_Gaussian
SEXP ComputeTestQuantRcpp_Gaussian(SEXP yin, SEXP Pyin, SEXP Xin, SEXP cov_matin, SEXP Din, SEXP tauin);
RcppExport SEXP _SPARK_ComputeTestQuantRcpp_Gaussian(SEXP yinSEXP, SEXP PyinSEXP, SEXP XinSEXP, SEXP cov_matinSEXP, SEXP DinSEXP, SEXP tauinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type yin(yinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Pyin(PyinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xin(XinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cov_matin(cov_matinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Din(DinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauin(tauinSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeTestQuantRcpp_Gaussian(yin, Pyin, Xin, cov_matin, Din, tauin));
    return rcpp_result_gen;
END_RCPP
}
// ComputeWeightsRcpp
SEXP ComputeWeightsRcpp(SEXP Yin, SEXP num_kernelin, SEXP Phiin);
RcppExport SEXP _SPARK_ComputeWeightsRcpp(SEXP YinSEXP, SEXP num_kernelinSEXP, SEXP PhiinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Yin(YinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type num_kernelin(num_kernelinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Phiin(PhiinSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeWeightsRcpp(Yin, num_kernelin, Phiin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SPARK_rcpp_hello_world", (DL_FUNC) &_SPARK_rcpp_hello_world, 0},
    {"_SPARK_SysMatEigen", (DL_FUNC) &_SPARK_SysMatEigen, 1},
    {"_SPARK_SparseSysMatEigen", (DL_FUNC) &_SPARK_SparseSysMatEigen, 2},
    {"_SPARK_CovariatesAI", (DL_FUNC) &_SPARK_CovariatesAI, 6},
    {"_SPARK_noCovariatesAI", (DL_FUNC) &_SPARK_noCovariatesAI, 6},
    {"_SPARK_ComputeTestQuantRcpp_nocov", (DL_FUNC) &_SPARK_ComputeTestQuantRcpp_nocov, 5},
    {"_SPARK_ComputeTestQuantRcpp_cov", (DL_FUNC) &_SPARK_ComputeTestQuantRcpp_cov, 6},
    {"_SPARK_ComputeTestQuantRcpp_Gaussian", (DL_FUNC) &_SPARK_ComputeTestQuantRcpp_Gaussian, 6},
    {"_SPARK_ComputeWeightsRcpp", (DL_FUNC) &_SPARK_ComputeWeightsRcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SPARK(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
