# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_SPARK_rcpp_hello_world`)
}

#' Do inverse of sysmetric matrix 
#' @param Min A sysmetric matrix
#' 
#' @return A list
#' 
#' @export
SysMatEigen <- function(Min) {
    .Call(`_SPARK_SysMatEigen`, Min)
}

#' Do inverse of sparse sysmetric matrix 
#' @param Min A sysmetric matrix
#' @param num_topin The number of top eigen values
#' 
#' @return A list
#' 
#' @export
SparseSysMatEigen <- function(Min, num_topin) {
    .Call(`_SPARK_SparseSysMatEigen`, Min, num_topin)
}

#' Variance component estimation with covariates using Average Information algorithm
#' @param Yin Working vector
#' @param Xin Covariate matrix
#' @param Din Weight for each gene
#' @param tauin Initial value for variance component
#' @param fixtauin Variance component to be optimized
#' @param tolin Tolerance
#' 
#' @return A list
#' 
#' @export
CovariatesAI <- function(Yin, Xin, Din, tauin, fixtauin, tolin) {
    .Call(`_SPARK_CovariatesAI`, Yin, Xin, Din, tauin, fixtauin, tolin)
}

#' Variance component estimation without covariates using Average Information algorithm, float format
#' @param Yin Working vector
#' @param Xin Covariate matrix
#' @param Din Weight for each gene
#' @param tauin Initial value for variance component
#' @param fixtauin Variance component to be optimized
#' @param tolin Tolerance
#' 
#' @return A list
#' 
#' 
#' @export
noCovariatesAI <- function(Yin, Xin, Din, tauin, fixtauin, tolin) {
    .Call(`_SPARK_noCovariatesAI`, Yin, Xin, Din, tauin, fixtauin, tolin)
}

#' Compute the testing quantities without covariates, float format
#' @param yin Working vector
#' @param Pyin The vector P*y
#' @param cov_matin Kernel matrix to be tested
#' @param Din Weight for each gene
#' @param tauin Initial value for variance component
#' 
#' @return A list
#' 
#' 
#' @export
ComputeTestQuantRcpp_nocov <- function(yin, Pyin, cov_matin, Din, tauin) {
    .Call(`_SPARK_ComputeTestQuantRcpp_nocov`, yin, Pyin, cov_matin, Din, tauin)
}

#' Compute the testing quantities with covariates, float format
#' @param yin Working vector
#' @param Pyin The vector P*y
#' @param Xin Covariate matrix, including the intercept
#' @param cov_matin Kernel matrix to be tested
#' @param Din Weight for each gene
#' @param tauin Initial value for variance component
#' 
#' @return A list
#' 
#' 
#' @export
ComputeTestQuantRcpp_cov <- function(yin, Pyin, Xin, cov_matin, Din, tauin) {
    .Call(`_SPARK_ComputeTestQuantRcpp_cov`, yin, Pyin, Xin, cov_matin, Din, tauin)
}

#' Compute the testing quantities for linear mixed model, float format
#' @param yin Working vector
#' @param Pyin The vector P*y
#' @param Xin Covariate matrix, including the intercept
#' @param cov_matin Kernel matrix to be tested
#' @param Din Weight for each gene
#' @param tauin Initial value for variance component
#' 
#' @return A list
#' 
#' 
#' @export
ComputeTestQuantRcpp_Gaussian <- function(yin, Pyin, Xin, cov_matin, Din, tauin) {
    .Call(`_SPARK_ComputeTestQuantRcpp_Gaussian`, yin, Pyin, Xin, cov_matin, Din, tauin)
}

#' Compute the kernel weights using psedu-counts
#' @param Yin Working vector
#' @param num_kernelin The number of kernel matrices,  10
#' @param Phiin The kernel matrices and identity matrix,  10 + 1 
#' 
#' @return A list
#' 
#' @export
ComputeWeightsRcpp <- function(Yin, num_kernelin, Phiin) {
    .Call(`_SPARK_ComputeWeightsRcpp`, Yin, num_kernelin, Phiin)
}

